package config

type CfgKeys string

const (
	APP_PORT CfgKeys = "APP_PORT"
	APP_ENV  CfgKeys = "APP_ENV"

	POSTGRES_HOST                CfgKeys = "POSTGRES_HOST"
	POSTGRES_PORT                CfgKeys = "POSTGRES_PORT"
	POSTGRES_USER                CfgKeys = "POSTGRES_USER"
	POSTGRES_PASS                CfgKeys = "POSTGRES_PASS"
	POSTGRES_DBNAME              CfgKeys = "POSTGRES_DBNAME"
	POSTGRES_SSLMODE             CfgKeys = "POSTGRES_SSLMODE"
	POSTGRES_MAX_OPEN_CONNS      CfgKeys = "POSTGRES_MAX_OPEN_CONNS"
	POSTGRES_MAX_IDLE_CONNS      CfgKeys = "POSTGRES_MAX_IDLE_CONNS"
	POSTGRES_LIFETIME_OPEN_CONNS CfgKeys = "POSTGRES_LIFETIME_OPEN_CONNS"
	POSTGRES_LIFETIME_IDLE_CONNS CfgKeys = "POSTGRES_LIFETIME_IDLE_CONNS"
)
